CREATE TABLE "Attendance" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "attDesc" varchar,
  "type" varchar,
  "employeeID" int,
  "memberID" int
);

ALTER TABLE "Attendance" ADD FOREIGN KEY ("employeeID") REFERENCES "Employee" ("id");

ALTER TABLE "Attendance" ADD FOREIGN KEY ("memberID") REFERENCES "Member" ("id");