CREATE TABLE "Attendance" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "attDesc" varchar,
  "type" varchar,
  "memberID" int,
  "trainingID" int,
  "userID" int
);

ALTER TABLE "Attendance" ADD FOREIGN KEY ("employeeID") REFERENCES "Employee" ("id");

ALTER TABLE "Attendance" ADD FOREIGN KEY ("memberID") REFERENCES "Member" ("id");

ALTER TABLE "Attendance" ADD FOREIGN KEY ("trainingID") REFERENCES "Training" ("id");

ALTER TABLE "Attendance" ADD FOREIGN KEY ("userID") REFERENCES "User" ("id");
