CREATE TABLE "Login" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar,
  "password" varchar,
  "UserRoleID" int,
  "UserID" int
);


ALTER TABLE "Login" ADD FOREIGN KEY ("UserRoleID") REFERENCES "UserRole" ("id");

ALTER TABLE "Login" ADD FOREIGN KEY ("UserID") REFERENCES "User" ("id");