CREATE TABLE "User" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "surname" varchar,
  "email" varchar,
  "username" varchar,
  "password" bit,
  "addres" varchar,
  "userRoleID" int
);

ALTER TABLE "User" ADD FOREIGN KEY ("userRoleID") REFERENCES "UserRole" ("id");